### PR TITLE
Fixing some errors in Lessons 0, 1 & 2

### PR DESCRIPTION
**Pull request by aravinds-arv**
I might add more commits here so this pull request need not be merged immediately :)

### CODE REVIEW

**Comment by aravinds-arv** [comment]
I've made quite a few changes (to lessons 0, 1 & 2) but so far I've not changed any existing content (other than adding messages for footnotes).. I've only made a few stylistic changes like changing quotes to admonitions for consistency, linking external sources to the footnotes and also corrected a few typos/errors wherever I spotted them while reading. 

But I think some sections of some lessons could be improved. Particularly upto now I found the lesson 2.3 (conditional statements) to be a bit lengthy.. and having a lot of repeated points/concepts. Also I did go through #9 and I think a lot of what was planned for this project had been left unfinished. So I would like to know if I could take the initiative of continuing the efforts of the the previous maintainers and complete the rest of what was laid out in the roadmap.

@iitm-github-admin @Bharath314 awaiting your reply..

**Comment by Bharath314** [comment]
Hey @aravinds-arv , thanks for reviving this repo. I do not own it anymore, but I'm sure if you start contributing, it will become active again. I went through your commits, and I have to say that you have a good understanding of the (admittedly rudimentary 😅) style guide. Maybe we can restart this thing and make a really good book on python.

**Comment by aravinds-arv** [comment]
Wow I wasn't expecting such a fast reply thanks @Bharath314 ❤️. Yeah 😅 I really loved the way this textbook was implemented, the writing and more so it's overall look.. it just looks great in both mobile & desktop.. so I did a bit of digging and stumbled upon the material-mkdocs documentation.. and even published a website for my own notes taking inspiration from here (still a work in progress). Btw I am currently in my foundational level and have taken python this term so that's how I discovered this gem of a project.. excited to make it shine more ✨

So how do we go about this.. you don't have write access to the repo now?

**Comment by aravinds-arv** [comment]
👀

**Comment by Bharath314** [comment]
I'm sorry for the late response. I do have write access, so I have a gleaming green button in front of me. 😬
@podkarthik Can we go ahead and start working on the textbook?

**Comment by podkarthik** [comment]
@Bharath314 Yes, please go ahead. @aravinds-arv welcome!

**Comment by aravinds-arv** [comment]
@podkarthik 🤍 @Bharath314 no problem mate.. now that we've got the green light could you review the commits in this pull request and merge them. 

I guess from hereon I'll open a new PR for the changes I make in each week. And for now I'll be keeping my focus on the following 
- Fixing the typos, broken links and other glaring errors that need immediate attention
- Some stylistic changes like use of footnotes and admonitions just to maintain consistency across lessons
- As I mentioned earlier, I'll try to improve sections or lessons that I feel could use a bit of revision/revamp

If I do find more time, I'll go through the other issues and try to work on the ones I feel most confident about :-)

**Pull request closed without merging**
